//! Golden-test harness (issue 0005): replay every case from golden.json —
//! generated by scripts/gen-golden.py with the EXACT torch the daemon links,
//! on MPS — through the in-process dispatch and assert exact agreement
//! (values via the same JSON serialization; errors by code).

use nutorchd::convert;
use nutorchd::dispatch;
use nutorchd::registry::Registry;
use tch::Device;

const GOLDEN: &str = include_str!("golden.json");

#[test]
fn golden_cases_agree_with_real_pytorch() {
    let cases: Vec<serde_json::Value> = serde_json::from_str(GOLDEN).expect("golden.json parses");
    assert!(cases.len() >= 25, "suspiciously few golden cases");

    let mut failures = Vec::new();
    for case in &cases {
        if let Err(message) = run_case(case) {
            failures.push(format!("{}: {message}", case["name"]));
        }
    }
    assert!(
        failures.is_empty(),
        "{} golden case(s) failed:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

fn run_case(case: &serde_json::Value) -> Result<(), String> {
    let mut registry = Registry::new();
    let op = case["op"].as_str().expect("op");
    let spec = nutorch_ops::find(op).ok_or_else(|| format!("op {op} not in table"))?;

    if let Some(seed) = case["seed"].as_i64() {
        tch::manual_seed(seed);
    }

    // Inputs: constructed exactly as the daemon would (dtype + MPS).
    let mut handles = Vec::new();
    for input in case["tensors"].as_array().expect("tensors") {
        let kind = convert::parse_kind(input["dtype"].as_str())
            .map_err(|e| format!("bad input dtype: {e}"))?;
        let tensor = convert::json_to_tensor(&input["data"], kind, Device::Mps)
            .map_err(|e| format!("bad input data: {e}"))?;
        handles.push(registry.insert(tensor));
    }

    let params = case["params"].as_object().cloned().unwrap_or_default();

    let response = dispatch::execute_table(&mut registry, spec, &handles, &params);
    let expect = &case["expect"];

    if let Some(expected_code) = expect["error"].as_str() {
        return match response {
            nutorchd::protocol::Response::Error { code, error, .. } => {
                if code == expected_code {
                    Ok(())
                } else {
                    Err(format!(
                        "expected code {expected_code}, got {code} ({error})"
                    ))
                }
            }
            other => Err(format!("expected error {expected_code}, got {other:?}")),
        };
    }

    if let Some(expected) = expect.get("value").filter(|_| expect["values"].is_null()) {
        return match response {
            nutorchd::protocol::Response::Value { value, .. } => {
                if &value == expected {
                    Ok(())
                } else {
                    Err(format!("expected value {expected}, got {value}"))
                }
            }
            other => Err(format!("expected a value, got {other:?}")),
        };
    }

    let expected_values = expect["values"].as_array().expect("values");
    let out_handles = match response {
        nutorchd::protocol::Response::Handles { handles, .. } => handles,
        other => return Err(format!("expected handles, got {other:?}")),
    };
    if out_handles.len() != expected_values.len() {
        return Err(format!(
            "expected {} output(s), got {}",
            expected_values.len(),
            out_handles.len()
        ));
    }
    for (handle, expected) in out_handles.iter().zip(expected_values) {
        let tensor = registry.get(handle).expect("output handle resolves");
        let cpu = tensor
            .f_to_device(Device::Cpu)
            .map_err(|e| format!("cpu copy failed: {e}"))?;
        let actual = convert::tensor_to_json(&cpu).map_err(|e| format!("serialize: {e}"))?;
        if &actual != expected {
            return Err(format!("expected {expected}, got {actual}"));
        }
    }
    Ok(())
}
