//! Golden-test harness (issue 0005): replay every case from golden.json —
//! generated by scripts/gen-golden.py with the EXACT torch the daemon links,
//! on MPS — through the in-process dispatch and assert exact agreement
//! (values via the same JSON serialization; errors by code).

use nutorchd::convert;
use nutorchd::dispatch;
use nutorchd::registry::Registry;
use tch::Device;

const GOLDEN: &str = include_str!("golden.json");

#[test]
fn golden_cases_agree_with_real_pytorch() {
    let cases: Vec<serde_json::Value> = serde_json::from_str(GOLDEN).expect("golden.json parses");
    assert!(cases.len() >= 253, "suspiciously few golden cases");

    let mut failures = Vec::new();
    for case in &cases {
        if let Err(message) = run_case(case) {
            failures.push(format!("{}: {message}", case["name"]));
        }
    }
    assert!(
        failures.is_empty(),
        "{} golden case(s) failed:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

fn run_case(case: &serde_json::Value) -> Result<(), String> {
    if case.get("grad_op").is_some() {
        return run_grad_case(case);
    }
    if case.get("nn_linear_forward").is_some() {
        return run_nn_linear_case(case);
    }
    if case.get("optim_step").is_some() {
        return run_optim_case(case);
    }
    if case.get("nn_module_forward").is_some() {
        return run_nn_module_case(case);
    }
    let mut registry = Registry::new();
    let op = case["op"].as_str().expect("op");
    let spec = nutorch_ops::find(op).ok_or_else(|| format!("op {op} not in table"))?;

    if let Some(seed) = case["seed"].as_i64() {
        tch::manual_seed(seed);
    }

    // Inputs: constructed exactly as the daemon would (dtype + MPS).
    let mut handles = Vec::new();
    for input in case["tensors"].as_array().expect("tensors") {
        let kind = convert::parse_kind(input["dtype"].as_str())
            .map_err(|e| format!("bad input dtype: {e}"))?;
        let tensor = convert::json_to_tensor(&input["data"], kind, Device::Mps)
            .map_err(|e| format!("bad input data: {e}"))?;
        handles.push(registry.insert_tensor(tensor));
    }

    // HandleOrScalar convention: a param value "T<i>" refers to input
    // tensor i — substitute its handle and exclude it from the operand list.
    let mut params = case["params"].as_object().cloned().unwrap_or_default();
    let mut referenced: Vec<usize> = Vec::new();
    for (_, value) in params.iter_mut() {
        if let Some(text) = value.as_str() {
            if let Some(index) = text.strip_prefix('T').and_then(|n| n.parse::<usize>().ok()) {
                referenced.push(index);
                *value = serde_json::Value::String(handles[index].clone());
            }
        }
    }
    let operands: Vec<String> = handles
        .iter()
        .enumerate()
        .filter(|(i, _)| !referenced.contains(i))
        .map(|(_, h)| h.clone())
        .collect();

    let response = dispatch::execute_table(&mut registry, spec, &operands, &params);
    let expect = &case["expect"];

    if let Some(expected_code) = expect["error"].as_str() {
        return match response {
            nutorchd::protocol::Response::Error { code, error, .. } => {
                if code == expected_code {
                    Ok(())
                } else {
                    Err(format!(
                        "expected code {expected_code}, got {code} ({error})"
                    ))
                }
            }
            other => Err(format!("expected error {expected_code}, got {other:?}")),
        };
    }

    if let Some(expected) = expect.get("value").filter(|_| expect["values"].is_null()) {
        return match response {
            nutorchd::protocol::Response::Value { value, .. } => {
                if &value == expected {
                    Ok(())
                } else {
                    Err(format!("expected value {expected}, got {value}"))
                }
            }
            other => Err(format!("expected a value, got {other:?}")),
        };
    }

    let expected_values = expect["values"].as_array().expect("values");
    let out_handles = match response {
        nutorchd::protocol::Response::Handles { handles, .. } => handles,
        other => return Err(format!("expected handles, got {other:?}")),
    };
    if out_handles.len() != expected_values.len() {
        return Err(format!(
            "expected {} output(s), got {}",
            expected_values.len(),
            out_handles.len()
        ));
    }
    for (handle, expected) in out_handles.iter().zip(expected_values) {
        let tensor = registry.get_tensor(handle).expect("output handle resolves");
        let cpu = tensor
            .f_to_device(Device::Cpu)
            .map_err(|e| format!("cpu copy failed: {e}"))?;
        let actual = convert::tensor_to_json(&cpu).map_err(|e| format!("serialize: {e}"))?;
        if &actual != expected {
            return Err(format!("expected {expected}, got {actual}"));
        }
    }
    Ok(())
}

/// Gradient golden (issue 0008): x (requires_grad leaf, set POST-transfer
/// — the .to() non-leaf trap) -> op -> loss (sum, or (y*y).sum() for
/// degenerate-loss ops) -> backward -> grad, compared exactly vs Python.
fn run_grad_case(case: &serde_json::Value) -> Result<(), String> {
    let mut registry = Registry::new();
    let op = case["grad_op"].as_str().expect("grad_op");
    let input = &case["input"];
    let kind = convert::parse_kind(input["dtype"].as_str())
        .map_err(|e| format!("bad input dtype: {e}"))?;
    let tensor = convert::json_to_tensor(&input["data"], kind, Device::Mps)
        .map_err(|e| format!("bad input data: {e}"))?
        .set_requires_grad(true);
    let x = registry.insert_tensor(tensor);

    let run = |registry: &mut Registry, name: &str, handles: &[String], params| {
        let spec = nutorch_ops::find(name).ok_or_else(|| format!("op {name} not in table"))?;
        match dispatch::execute_table(registry, spec, handles, &params) {
            nutorchd::protocol::Response::Handles { handles, .. } => Ok(handles),
            nutorchd::protocol::Response::Value { .. } => Ok(Vec::new()),
            other => Err(format!("{name}: unexpected response {other:?}")),
        }
    };

    let params = case["params"].as_object().cloned().unwrap_or_default();
    let operands: Vec<String> = if case["with_self"].as_bool().unwrap_or(false) {
        vec![x.clone(), x.clone()]
    } else if case.get("target").is_some_and(|t| !t.is_null()) {
        // A DISTINCT non-grad leaf (loss targets carry no gradient).
        let target = &case["target"];
        let kind = convert::parse_kind(target["dtype"].as_str())
            .map_err(|e| format!("bad target dtype: {e}"))?;
        let tensor = convert::json_to_tensor(&target["data"], kind, Device::Mps)
            .map_err(|e| format!("bad target data: {e}"))?;
        vec![x.clone(), registry.insert_tensor(tensor)]
    } else {
        vec![x.clone()]
    };
    let y = run(&mut registry, op, &operands, params)?
        .first()
        .cloned()
        .ok_or("op produced no handle")?;

    let loss = if case["skip_sum"].as_bool().unwrap_or(false) {
        // Losses with mean reduction are already scalar.
        y.clone()
    } else if case["square_loss"].as_bool().unwrap_or(false) {
        let squared = run(
            &mut registry,
            "mul",
            &[y.clone(), y.clone()],
            serde_json::Map::new(),
        )?
        .first()
        .cloned()
        .ok_or("mul produced no handle")?;
        run(&mut registry, "sum", &[squared], serde_json::Map::new())?
            .first()
            .cloned()
            .ok_or("sum produced no handle")?
    } else {
        run(&mut registry, "sum", &[y], serde_json::Map::new())?
            .first()
            .cloned()
            .ok_or("sum produced no handle")?
    };

    run(&mut registry, "backward", &[loss], serde_json::Map::new())?;
    let grad = run(&mut registry, "grad", &[x], serde_json::Map::new())?
        .first()
        .cloned()
        .ok_or("grad produced no handle")?;

    let cpu = registry
        .get_tensor(&grad)
        .expect("grad handle resolves")
        .f_to_device(Device::Cpu)
        .map_err(|e| format!("cpu copy failed: {e}"))?;
    let actual = convert::tensor_to_json(&cpu).map_err(|e| format!("serialize: {e}"))?;
    let expected = &case["expect_grad"];
    if &actual != expected {
        return Err(format!("expected grad {expected}, got {actual}"));
    }
    Ok(())
}

/// nn golden (issue 0009): construct linear with EXPLICIT weights via the
/// bespoke dispatch, optionally chain activations via sequential, forward
/// a known input, then backward and compare weight/bias grads — all
/// against torch.nn.functional on MPS.
fn run_nn_linear_case(case: &serde_json::Value) -> Result<(), String> {
    use nutorchd::lifecycle::Lifecycle;
    use std::path::PathBuf;
    use std::sync::Mutex;

    let mut registry = Registry::new();
    let lifecycle = Mutex::new(Lifecycle::new(None));
    let socket = PathBuf::from("/tmp/golden.sock");
    let bespoke = |registry: &mut Registry,
                   request: serde_json::Value|
     -> Result<serde_json::Value, String> {
        let parsed = dispatch::parse_request(&request.to_string())
            .map_err(|response| format!("parse: {response:?}"))?;
        let (response, _) = dispatch::handle_request(registry, &lifecycle, &socket, parsed);
        match response {
            nutorchd::protocol::Response::Handle { handle, .. } => {
                Ok(serde_json::Value::String(handle))
            }
            nutorchd::protocol::Response::Handles { handles, .. } => Ok(serde_json::json!(handles)),
            nutorchd::protocol::Response::Value { value, .. } => Ok(value),
            other => Err(format!("bespoke: unexpected {other:?}")),
        }
    };

    // Inputs and explicit weights.
    let make = |registry: &mut Registry, data: &serde_json::Value| -> Result<String, String> {
        let t = convert::json_to_tensor(data, tch::Kind::Float, Device::Mps)
            .map_err(|e| format!("input: {e}"))?;
        Ok(registry.insert_tensor(t))
    };
    let x = make(&mut registry, &case["input"])?;
    let w = make(&mut registry, &case["weight"])?;
    let mut args = serde_json::json!({ "weight": w });
    if case["bias"].is_null() {
        args["no_bias"] = serde_json::json!(true);
    } else {
        let b = make(&mut registry, &case["bias"])?;
        args["bias_tensor"] = serde_json::json!(b);
    }
    let shape = case["weight"].as_array().unwrap();
    args["out_features"] = serde_json::json!(shape.len() as i64);
    args["in_features"] = serde_json::json!(shape[0].as_array().unwrap().len() as i64);
    let linear = bespoke(
        &mut registry,
        serde_json::json!({"op":"nn","kind":"linear","args": args}),
    )?;
    let linear = linear.as_str().unwrap().to_string();

    // Optional activation chain via sequential composition.
    let model = if case["chain"].as_array().is_some_and(|c| !c.is_empty()) {
        let mut children = vec![serde_json::Value::String(linear.clone())];
        for activation in case["chain"].as_array().unwrap() {
            let child = bespoke(
                &mut registry,
                serde_json::json!({"op":"nn","kind": activation, "args": {}}),
            )?;
            children.push(child);
        }
        let composed = bespoke(
            &mut registry,
            serde_json::json!({"op":"nn","kind":"sequential","args":{"children": children}}),
        )?;
        composed.as_str().unwrap().to_string()
    } else {
        linear
    };

    // Forward, check output.
    let y = bespoke(
        &mut registry,
        serde_json::json!({"op":"forward","module": model, "tensor": x}),
    )?;
    let y = y.as_str().unwrap().to_string();
    let to_json = |registry: &Registry, handle: &str| -> Result<serde_json::Value, String> {
        let cpu = registry
            .get_tensor(handle)
            .map_err(|l| l.message())?
            .f_to_device(Device::Cpu)
            .map_err(|e| format!("cpu: {e}"))?;
        convert::tensor_to_json(&cpu).map_err(|e| format!("json: {e}"))
    };
    let actual = to_json(&registry, &y)?;
    if &actual != &case["expect_output"] {
        return Err(format!(
            "output: expected {}, got {actual}",
            case["expect_output"]
        ));
    }

    // Backward through sum; compare parameter grads via live views.
    let table =
        |registry: &mut Registry, op: &str, handles: &[String]| -> Result<Vec<String>, String> {
            let spec = nutorch_ops::find(op).ok_or_else(|| format!("{op} not in table"))?;
            match dispatch::execute_table(registry, spec, handles, &serde_json::Map::new()) {
                nutorchd::protocol::Response::Handles { handles, .. } => Ok(handles),
                other => Err(format!("{op}: unexpected {other:?}")),
            }
        };
    let loss = table(&mut registry, "sum", &[y])?[0].clone();
    table(&mut registry, "backward", &[loss]).ok(); // ResultKind::None → Value resp; ignore shape
    let params = bespoke(
        &mut registry,
        serde_json::json!({"op":"nn_parameters","module": model}),
    )?;
    let params: Vec<String> = serde_json::from_value(params).map_err(|e| e.to_string())?;
    let weight_grad = table(&mut registry, "grad", &[params[0].clone()])?[0].clone();
    let actual = to_json(&registry, &weight_grad)?;
    if &actual != &case["expect_weight_grad"] {
        return Err(format!(
            "weight grad: expected {}, got {actual}",
            case["expect_weight_grad"]
        ));
    }
    if !case["expect_bias_grad"].is_null() {
        let bias_grad = table(&mut registry, "grad", &[params[1].clone()])?[0].clone();
        let actual = to_json(&registry, &bias_grad)?;
        if &actual != &case["expect_bias_grad"] {
            return Err(format!(
                "bias grad: expected {}, got {actual}",
                case["expect_bias_grad"]
            ));
        }
    }
    Ok(())
}

/// Optimizer golden (issue 0009 exp 4): explicit-weight linear, mse loss,
/// 3 steps of torch.optim's trajectory, weights compared after each.
fn run_optim_case(case: &serde_json::Value) -> Result<(), String> {
    use nutorchd::lifecycle::Lifecycle;
    use std::path::PathBuf;
    use std::sync::Mutex;

    let mut registry = Registry::new();
    let lifecycle = Mutex::new(Lifecycle::new(None));
    let socket = PathBuf::from("/tmp/golden.sock");
    let bespoke = |registry: &mut Registry,
                   request: serde_json::Value|
     -> Result<serde_json::Value, String> {
        let parsed = dispatch::parse_request(&request.to_string())
            .map_err(|response| format!("parse: {response:?}"))?;
        let (response, _) = dispatch::handle_request(registry, &lifecycle, &socket, parsed);
        match response {
            nutorchd::protocol::Response::Handle { handle, .. } => {
                Ok(serde_json::Value::String(handle))
            }
            nutorchd::protocol::Response::Handles { handles, .. } => Ok(serde_json::json!(handles)),
            nutorchd::protocol::Response::Value { value, .. } => Ok(value),
            other => Err(format!("bespoke: unexpected {other:?}")),
        }
    };
    let table =
        |registry: &mut Registry, op: &str, handles: &[String]| -> Result<Vec<String>, String> {
            let spec = nutorch_ops::find(op).ok_or_else(|| format!("{op} not in table"))?;
            match dispatch::execute_table(registry, spec, handles, &serde_json::Map::new()) {
                nutorchd::protocol::Response::Handles { handles, .. } => Ok(handles),
                nutorchd::protocol::Response::Value { .. } => Ok(Vec::new()),
                other => Err(format!("{op}: unexpected {other:?}")),
            }
        };
    let make = |registry: &mut Registry, data: &serde_json::Value| -> Result<String, String> {
        let t = convert::json_to_tensor(data, tch::Kind::Float, Device::Mps)
            .map_err(|e| format!("input: {e}"))?;
        Ok(registry.insert_tensor(t))
    };

    let w0 = make(&mut registry, &case["weight0"])?;
    let x = make(&mut registry, &case["input"])?;
    let target = make(&mut registry, &case["target"])?;
    let out_features = case["weight0"].as_array().unwrap().len() as i64;
    let in_features = case["weight0"][0].as_array().unwrap().len() as i64;
    let linear = bespoke(
        &mut registry,
        serde_json::json!({"op":"nn","kind":"linear","args":{
            "in_features": in_features, "out_features": out_features,
            "weight": w0, "no_bias": true,
        }}),
    )?;
    let linear = linear.as_str().unwrap().to_string();

    // Optimizer over the module, hyperparams from the case.
    let kind = case["optim_step"].as_str().unwrap();
    let mut args = case["hyper"].clone();
    args["module"] = serde_json::json!(linear);
    let opt = bespoke(
        &mut registry,
        serde_json::json!({"op":"nn","kind": kind, "args": args}),
    )?;
    let opt = opt.as_str().unwrap().to_string();

    let expected_steps = case["expect_steps"].as_array().unwrap();
    for (step_index, expected) in expected_steps.iter().enumerate() {
        bespoke(
            &mut registry,
            serde_json::json!({"op":"nn_zero_grad","handle": opt}),
        )?;
        let pred = bespoke(
            &mut registry,
            serde_json::json!({"op":"forward","module": linear, "tensor": x}),
        )?;
        let pred = pred.as_str().unwrap().to_string();
        let loss = table(&mut registry, "mse_loss", &[pred, target.clone()])?[0].clone();
        table(&mut registry, "backward", &[loss])?;
        bespoke(
            &mut registry,
            serde_json::json!({"op":"step","optimizer": opt}),
        )?;

        // Read the module's weight via parameters (live view).
        let params = bespoke(
            &mut registry,
            serde_json::json!({"op":"nn_parameters","module": linear}),
        )?;
        let params: Vec<String> = serde_json::from_value(params).map_err(|e| e.to_string())?;
        let cpu = registry
            .get_tensor(&params[0])
            .map_err(|l| l.message())?
            .f_to_device(Device::Cpu)
            .map_err(|e| format!("cpu: {e}"))?;
        let actual = convert::tensor_to_json(&cpu).map_err(|e| format!("json: {e}"))?;
        if &actual != expected {
            return Err(format!(
                "step {}: expected {expected}, got {actual}",
                step_index + 1
            ));
        }
    }
    Ok(())
}

/// Module sweep golden (issue 0009 exp 5): construct kind (explicit
/// weights when parameterized), optional eval mode, forward a fixed
/// input, compare exactly vs torch.nn.functional on MPS.
fn run_nn_module_case(case: &serde_json::Value) -> Result<(), String> {
    use nutorchd::lifecycle::Lifecycle;
    use std::path::PathBuf;
    use std::sync::Mutex;

    let mut registry = Registry::new();
    let lifecycle = Mutex::new(Lifecycle::new(None));
    let socket = PathBuf::from("/tmp/golden.sock");
    let bespoke = |registry: &mut Registry,
                   request: serde_json::Value|
     -> Result<serde_json::Value, String> {
        let parsed = dispatch::parse_request(&request.to_string())
            .map_err(|response| format!("parse: {response:?}"))?;
        let (response, _) = dispatch::handle_request(registry, &lifecycle, &socket, parsed);
        match response {
            nutorchd::protocol::Response::Handle { handle, .. } => {
                Ok(serde_json::Value::String(handle))
            }
            nutorchd::protocol::Response::Value { value, .. } => Ok(value),
            other => Err(format!("bespoke: unexpected {other:?}")),
        }
    };

    let kind = case["nn_module_forward"].as_str().unwrap();
    let mut cargs = case["cargs"].as_object().cloned().unwrap_or_default();
    for (field, arg) in [("weight", "weight"), ("bias", "bias_tensor")] {
        if !case[field].is_null() {
            let t = convert::json_to_tensor(&case[field], tch::Kind::Float, Device::Mps)
                .map_err(|e| format!("{field}: {e}"))?;
            let h = registry.insert_tensor(t);
            cargs.insert(arg.to_string(), serde_json::Value::String(h));
        }
    }
    let module = bespoke(
        &mut registry,
        serde_json::json!({"op":"nn","kind": kind, "args": cargs}),
    )?;
    let module = module.as_str().unwrap().to_string();
    if case["eval_mode"].as_bool().unwrap_or(false) {
        bespoke(
            &mut registry,
            serde_json::json!({"op":"nn_mode","module": module, "train": false}),
        )?;
    }

    let input = &case["input"];
    let input_kind =
        convert::parse_kind(input["dtype"].as_str()).map_err(|e| format!("input dtype: {e}"))?;
    let x = registry.insert_tensor(
        convert::json_to_tensor(&input["data"], input_kind, Device::Mps)
            .map_err(|e| format!("input: {e}"))?,
    );
    let y = bespoke(
        &mut registry,
        serde_json::json!({"op":"forward","module": module, "tensor": x}),
    )?;
    let y = y.as_str().unwrap().to_string();
    let cpu = registry
        .get_tensor(&y)
        .map_err(|l| l.message())?
        .f_to_device(Device::Cpu)
        .map_err(|e| format!("cpu: {e}"))?;
    let actual = convert::tensor_to_json(&cpu).map_err(|e| format!("json: {e}"))?;
    if &actual != &case["expect_output"] {
        return Err(format!("expected {}, got {actual}", case["expect_output"]));
    }
    Ok(())
}
